version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: identity-db
    environment:
      - POSTGRES_USER=${IDENTITY_DB_USER}
      - POSTGRES_PASSWORD=${IDENTITY_DB_PASSWORD}
      - POSTGRES_DB=${IDENTITY_DB_NAME}
    ports:
      - "${IDENTITY_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge